<a href="https://colab.research.google.com/github/preetu1912/preetu_aiml/blob/main/labsheet3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# New section

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [ ]:
import pandas as pd # Make sure pandas is imported with the alias 'pd'
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:

df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [3]:
import pandas as pd

# Assuming the CSV file path is correct:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

print(df.shape)
print(df.columns)

(3000, 9)
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [5]:
import pandas as pd

# Assuming the CSV file path is correct:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

# Assuming 'total_rooms','total_bedrooms','population','households','median_income' are your features:
X = df[['total_rooms','total_bedrooms','population','households','median_income']]
# Assuming 'median_house_value' is your target variable:
y = df['median_house_value']

print(X)

      total_rooms  total_bedrooms  population  households  median_income
0          3885.0           661.0      1537.0       606.0         6.6085
1          1510.0           310.0       809.0       277.0         3.5990
2          3589.0           507.0      1484.0       495.0         5.7934
3            67.0            15.0        49.0        11.0         6.1359
4          1241.0           244.0       850.0       237.0         2.9375
...           ...             ...         ...         ...            ...
2995       1450.0           642.0      1258.0       607.0         1.1790
2996       5257.0          1082.0      3496.0      1036.0         3.3906
2997        956.0           201.0       693.0       220.0         2.2895
2998         96.0            14.0        46.0        14.0         3.2708
2999       1765.0           263.0       753.0       260.0         8.5608

[3000 rows x 5 columns]

In [6]:


print(X)

      total_rooms  total_bedrooms  population  households  median_income
0          3885.0           661.0      1537.0       606.0         6.6085
1          1510.0           310.0       809.0       277.0         3.5990
2          3589.0           507.0      1484.0       495.0         5.7934
3            67.0            15.0        49.0        11.0         6.1359
4          1241.0           244.0       850.0       237.0         2.9375
...           ...             ...         ...         ...            ...
2995       1450.0           642.0      1258.0       607.0         1.1790
2996       5257.0          1082.0      3496.0      1036.0         3.3906
2997        956.0           201.0       693.0       220.0         2.2895
2998         96.0            14.0        46.0        14.0         3.2708
2999       1765.0           263.0       753.0       260.0         8.5608

[3000 rows x 5 columns]

In [ ]:

print(X.shape)
print(y.shape)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

NameError: name 'X_train' is not defined

In [ ]:

from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [ ]:
lm.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [ ]:

y_pred = lm.predict(X_test)

NameError: name 'X_test' is not defined

In [ ]:

plt.scatter(X_train,y_train,color='green')
plt.plot(X_train,lm.predict(X_train),color='blue')
plt.title('Training Data')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.show()

NameError: name 'X_train' is not defined

In [ ]:

slope = lm.coef_
intercept = lm.intercept_
print("estimated model slope:",slope)
print("estmated model intercept",intercept)

NameError: name 'lm' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression

# Assuming X_train and y_train are defined
lm = LinearRegression() # define the variable lm
lm.fit(X_train,y_train)

y_pred = lm.predict(X_test)

plt.scatter(X_train,y_train,color='green')
plt.plot(X_train,lm.predict(X_train),color='blue')
plt.title('Training Data')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.show()

slope = lm.coef_
intercept = lm.intercept_
print("estimated model slope:",slope)
print("estmated model intercept",intercept)

NameError: name 'X_train' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np  # Import numpy for array creation

# Sample data (replace with your actual data)
X_train = np.array([[100], [150], [200], [250], [300]])  # Example TV advertising spending
y_train = np.array([10], [15], [20], [25], [30]])  # Example Sales

lm = LinearRegression()  # define the variable lm
lm.fit(X_train, y_train)

# ... rest of your code ...

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-29-d7d3b4ecb6c1>, line 6)

In [ ]:
X_new=[[200]]

In [ ]:

lm.predict(X_new)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Sample data (replace with your actual data)
X_train = np.array([[100], [150], [200], [250], [300]])  # Example TV advertising spending
y_train = np.array([10], [15], [20], [25], [30]])  # Example Sales

X_new=[[200]]

lm = LinearRegression()  # define the variable lm
lm.fit(X_train, y_train) # fit the model before predicting

lm.predict(X_new)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-31-087535c56555>, line 6)

In [ ]:
array([[18.10369721]])